
resources:
  - slides/**

author: "Eugeni Vidal-Tortosa"

project:
  type: website
  output-dir: .

website:
  favicon: images/favicon.png
  navbar:
    pinned: false
    background: white
    foreground: black
    
    left:
      - text: "Eugeni Vidal-Tortosa"
        href: index.qmd
      # - text: Home
      #   href: index.qmd  
      - text: Projects
        href: projects.qmd
      - text: Publications
        href: publications.qmd
      - text: Materials
        href: materials.qmd
      # - text: Notebook
      #   href: notebook.qmd
      - text: CV
        href: cv.qmd
      # - text: News
      #   href: updates.qmd
    right:
     - id: language-menu
       icon: globe
       menu:
          - text: "English"
            href: index.html
          - text: "Catalan"
            href: ca/index.html

  page-footer:
    center: "© 2026 Eugeni Vidal-Tortosa • Designed and built with Quarto"

format:
  html:
    css: styles.css
    theme: cosmo
    toc: false
    page-layout: article
    title-block-banner: false
    include-in-header:
      text: |
        <meta name="google-site-verification" content="ddPZrTz8TuaEweUTnEQgxnHoVmd_y_unirRTl_BbVFE" />
