resources:
  - ../slides/**

author: "Eugeni Vidal-Tortosa"

project:
  type: website
  output-dir: .

website:
  favicon: ../images/favicon.png
  navbar:
    pinned: false
    background: white
    foreground: black

    left:
      - text: "Eugeni Vidal-Tortosa"
        href: index.qmd
      - text: Projectes
        href: projectes.qmd
      - text: Publicacions
        href: publicacions.qmd
      - text: Materials
        href: materials.qmd
      - text: CV
        href: cv.qmd
    right:
     - id: language-menu
       icon: globe
       menu:
        - text: "Anglès"
          href: ../index.html
        - text: "Català"
          href: index.html

  page-footer:
    center: "© 2026 Eugeni Vidal-Tortosa • Dissenyat i creat amb Quarto"

format:
  html:
    css: ../styles.css
    theme: cosmo
    toc: false
    page-layout: article
    title-block-banner: false
    include-in-header:
      text: |
        <meta name="google-site-verification" content="ddPZrTz8TuaEweUTnEQgxnHoVmd_y_unirRTl_BbVFE" />